spring.application.name=PhoenixStore

# URL adaptada al formato JDBC
spring.datasource.url=jdbc:postgresql://dpg-cvoimqhr0fns739o7el0-a.oregon-postgres.render.com/phoenixstore_kfrx

# Credenciales de tu nueva base de datos
spring.datasource.username=phoenix
spring.datasource.password=Xsi7JJi8BrKgUEHWPNoUVFeodswyCa3M

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=4444

# Configuración JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
